FROM node:14 as builder

WORKDIR /app

COPY package.json .

RUN npm install

FROM alpine

RUN apk add --update nodejs

WORKDIR /app

COPY src /app

COPY --from=builder /app/node_modules /app/node_modules

ENTRYPOINT [ "node", "app.js" ]