version: '3'

services:
    unfurler:
        build: .
        environment:
            - GITLAB_TOKEN=${GITLAB_TOKEN}
            - GITLAB_URL=${GITLAB_URL}
            - SLACK_OAUTH_TOKEN=${SLACK_OAUTH_TOKEN}
            - PORT=${PORT:-3000}
        volumes:
            - ./src:/app/src
        ports:
            - 3000:3000
